export interface FlashCard {
  t: string;
  p: string;
  au: string;
  reflect: string;
}

export interface KeyCheckQuestion {
  q: string;
  options: string[];
  correct: number;
}

export interface Module {
  title: string;
  label: string;
  desc: string;
  relatedPractice: string;
  cards: FlashCard[];
  keyCheckQuestions: KeyCheckQuestion[];
}

export interface PracticeItem {
  id: string;
  label: string;
  mechanisms?: number[];
  title: string;
  subtitle: string;
  sourceLabel: string;
  postText: string;
  contextText: string;
  q1: string;
  q1Options: string[];
  q1Correct: number;
  q2Question: string;
  q2Options: string[];
  q2Correct: string;
  q2Verdict: string;
  explanation: string;
  tactic: string;
  reference: string;
  event: string;
}

export interface AssessItem {
  pairId: string;
  skill: string;
  difficulty: string;
  sourceLabel: string;
  postText: string;
  question: string;
  options: string[];
  correctIndex: number;
}

export interface AssessSection {
  title: string;
  intro: string;
  scoreField: string;
  completionLabel: string;
  items: AssessItem[];
}

export const moduleData: Module[] = [
  {
    title: "Claim Identification",
    label: "Mechanism 01",
    desc: "Extracting verifiable statements from political noise.",
    relatedPractice: "scenario-01",
    cards: [
      { t: "What is a Claim?", p: "A claim is a statement that asserts something about the world that can be tested or verified with evidence. Claims differ from feelings, wishes, or vague impressions.", au: "During the 2025 Federal Budget, the Treasurer stated \"We created 1.2 million jobs in three years.\" Verifiable against ABS employment data — a claim, not an opinion.", reflect: "Can this statement be proven true or false with evidence?" },
      { t: "Claim vs Opinion", p: "An opinion expresses a feeling or judgement. A claim makes an assertion about the world that can be tested.", au: "\"I do not trust this result\" is an opinion, while \"votes were changed after counting\" is a claim.", reflect: "Not every sentence in a post should be treated as evidence-based." },
      { t: "Types of Claims", p: "Claims can be factual (something happened), predictive (something will happen), or causal (X caused Y). Each type requires different evidence.", au: "Voice Referendum — Factual: \"The referendum was held on 14 October 2023.\" Causal: \"The No campaign caused record youth enrolment.\"", reflect: "Identify the type of claim before seeking evidence." },
      { t: "Verifying Claims", p: "Good verification uses primary sources: government data, peer-reviewed research, official transcripts, or reputable independent bodies.", au: "To verify an AEC claim about voter turnout, consult AEC official results — not news summaries or social media posts.", reflect: "Always trace claims back to primary, citable sources." },
      { t: "Where claims appear", p: "Claims can appear in headlines, captions, memes, comments, rumours, and quoted \"insider\" language.", au: "Australian election rumours often use short captions or screenshots to disguise a bold claim.", reflect: "Always identify the core statement before deciding whether it is true or false." },
    ],
    keyCheckQuestions: [
      { q: "What is a claim?", options: ["A statement that can be checked with evidence","An emotional opinion about politics","Any sentence that sounds important or urgent"], correct: 0 },
      { q: "How do you separate a claim from an opinion?", options: ["Claims always use stronger language than opinions","Claims assert something factual that can be tested; opinions express judgement or feeling","Opinions are always shorter and simpler than claims"], correct: 1 },
      { q: "What should you do FIRST when reading political content?", options: ["Immediately judge whether it is true or false","Identify the specific verifiable statement being made","Check how many likes or shares the post has received"], correct: 1 },
      { q: "Which of these is a claim (not an opinion)?", options: ["\"I feel the government is not doing enough\"","\"The unemployment rate rose by 0.3% last quarter\"","\"This policy is clearly a disaster\""], correct: 1 },
      { q: "Where can political claims appear?", options: ["Only in official government press releases","Only in newspaper headlines","In headlines, memes, captions, comments, and rumours"], correct: 2 },
    ],
  },
  {
    title: "False Authority",
    label: "Mechanism 02",
    desc: "Misleading appeals to expert credibility.",
    relatedPractice: "scenario-06",
    cards: [
      { t: "What is False Authority?", p: "False Authority occurs when someone is cited as an expert outside their actual expertise, or credentials are inflated to lend credibility to a claim.", au: "A celebrity chef appearing in a political ad to comment on economic policy — culinary expertise does not transfer to macroeconomics.", reflect: "Is this person actually an expert in the relevant field?" },
      { t: "How to respond", p: "Return to the claim itself. Ask what concrete evidence supports it, not who allegedly said it.", au: "If the post only cites unnamed experts, the claim may be unsupported or misleading.", reflect: "Move from who is talking to what can actually be checked." },
      { t: "Red Flags", p: "Watch for vague credentials (\"experts say\"), unnamed sources, official-sounding titles, and appeals to fame over expertise.", au: "A 2025 Queensland election pamphlet cited \"independent analysts\" without naming them — a classic red flag.", reflect: "Unnamed experts and vague institutions are always red flags." },
      { t: "Legitimate vs False", p: "Legitimate authority comes from relevant qualifications and peer review within a specific field. False authority borrows credibility from unrelated domains.", au: "ANU political scientist on electoral law = legitimate. Mining CEO on climate science = false authority.", reflect: "Match the expert's field to the specific claim being made." },
      { t: "Why It Works", p: "We are wired to trust authority figures. False Authority exploits this cognitive shortcut to bypass critical evaluation.", au: "In the 2023 Voice Referendum, ads featured individuals with professional titles unrelated to constitutional law — but the title alone prompted trust.", reflect: "Credentials create a feeling of trust — verify that feeling with evidence." },
    ],
    keyCheckQuestions: [
      { q: "What is False Authority?", options: ["Citing someone with real expertise in the right field","Citing someone whose expertise does not apply to the claim being made","Ignoring all experts to rely on personal experience"], correct: 1 },
      { q: "Which is a red flag for False Authority?", options: ["\"According to the AEC's published guidelines...\"","\"Experts agree — though none are named\"","\"The Reserve Bank's latest report shows...\""], correct: 1 },
      { q: "An Olympic swimmer endorses an economic policy. What is the concern?", options: ["The swimmer has no credibility at all","Swimming expertise does not transfer to economic policy","Olympic athletes are always biased on political matters"], correct: 1 },
      { q: "How do you counter False Authority?", options: ["Accept the claim because of the impressive title","Check if the expert's field matches the specific claim being made","Reject all expert opinion regardless of relevance"], correct: 1 },
      { q: "Legitimate authority in a political claim comes from...", options: ["Famous people regardless of their field","Relevant qualifications and peer review in the specific domain","Whoever speaks with the most confidence"], correct: 1 },
    ],
  },
  {
    title: "Emotional Framing",
    label: "Mechanism 03",
    desc: "Using emotion to bypass rational evaluation.",
    relatedPractice: "scenario-11",
    cards: [
      { t: "What is Emotional Framing?", p: "Emotional Framing uses language, imagery, or tone to trigger strong feelings — fear, outrage, pride — making claims seem more compelling than evidence supports.", au: "A political ad showing crime statistics overlaid with dark music and distressed faces frames a claim emotionally to create disproportionate fear.", reflect: "Is the emotional tone proportional to the actual evidence?" },
      { t: "Fear as a Tactic", p: "Fear is the most commonly used emotion in political messaging. It activates threat-response thinking, reducing careful evaluation of evidence.", au: "In the 2025 federal election, messaging about \"waves of illegal migration\" used fear language disproportionate to actual immigration data.", reflect: "When you feel fear from a claim, pause and verify the statistics separately." },
      { t: "Spotting the Frame", p: "Emotional frames appear in word choice. \"Invasion\" vs \"migration\", \"death panels\" vs \"end-of-life care\". Facts may be the same; the frame shapes your response.", au: "\"Asylum seeker\" and \"illegal immigrant\" can describe the same person — each carries very different emotional weight in Australian political discourse.", reflect: "Identify the emotional charge of the words, then seek neutral language alternatives." },
    ],
    keyCheckQuestions: [
      { q: "What is Emotional Framing?", options: ["Reporting facts without any perspective","Using emotional language or imagery to shape how a claim feels rather than what it proves","Providing detailed evidence alongside a claim"], correct: 1 },
      { q: "Which word pairs show Emotional Framing?", options: ["\"Increase\" vs \"rise\"","\"Invasion\" vs \"migration\"","\"Budget\" vs \"finance\""], correct: 1 },
      { q: "When you feel strong fear or outrage from political content, what should you do first?", options: ["Share it immediately so others can respond","Pause and check the actual statistics or evidence separately","Dismiss it completely as propaganda"], correct: 1 },
    ],
  },
  {
    title: "Selective Evidence",
    label: "Mechanism 04",
    desc: "Cherry-picking data to support a narrative.",
    relatedPractice: "scenario-21",
    cards: [
      { t: "What is Selective Evidence?", p: "Selective Evidence involves choosing only data points that support a position while ignoring contradictory evidence — also called \"cherry-picking\".", au: "Citing one month of rising employment to claim the economy is thriving while ignoring six months of declining real wages.", reflect: "What evidence might exist that contradicts this claim?" },
      { t: "The Full Picture", p: "Honest argument acknowledges counter-evidence. When sources only cite supporting evidence, that is a sign of selective presentation.", au: "During the 2025 NDIS debate, one side cited cost blowout figures while ignoring published quality-of-life improvements for participants.", reflect: "Demand the full dataset, not a curated sample." },
      { t: "Anecdote vs Data", p: "A single story is not evidence of a trend. Selective anecdotes make rare events appear common and distort perception of scale.", au: "One welfare fraud case reported nationally creates the impression of widespread abuse — when ATO data shows fraud below 1% of claims.", reflect: "An anecdote illustrates; it does not prove. Seek aggregate data." },
    ],
    keyCheckQuestions: [
      { q: "What is Selective Evidence?", options: ["Using all available data to form a balanced conclusion","Choosing only supporting data while ignoring contradictory evidence","Presenting two opposing views fairly"], correct: 1 },
      { q: "What is the key question to ask about Selective Evidence?", options: ["\"How many people shared this?\"","\"What evidence might exist that contradicts this claim?\"","\"Does the author seem trustworthy?\""], correct: 1 },
      { q: "A single welfare fraud story reported nationally represents...", options: ["Proof that fraud is widespread","An anecdote that illustrates but does not prove a trend","Definitive statistical evidence"], correct: 1 },
    ],
  },
  {
    title: "Misleading Statistics",
    label: "Mechanism 05",
    desc: "How numbers can deceive without lying.",
    relatedPractice: "scenario-26",
    cards: [
      { t: "What are Misleading Statistics?", p: "Statistics can be technically accurate but deeply misleading through selective framing, inappropriate comparisons, or manipulation of scale, base rates, or context.", au: "\"Crime increased 50% in our suburb\" — if that means 2 incidents became 3, the percentage sounds alarming but the base rate is tiny.", reflect: "50% of what? What is the base number?" },
      { t: "Absolute vs Relative Risk", p: "Relative risk sounds more dramatic than absolute risk. \"Doubles your chance\" sounds alarming — but going from 0.5% to 1% is very different in absolute terms.", au: "A drug policy ad claiming a substance \"doubles the risk of psychosis\" failed to mention the base rate was 0.5% — a 0.5 percentage point absolute increase.", reflect: "Convert relative risk to absolute risk to understand true scale." },
      { t: "Misleading Graphs", p: "Graphs can lie through truncated axes, missing zero points, cherry-picked date ranges, or 3D distortions that make small differences look dramatic.", au: "In the 2024 cost-of-living debate, a graph starting from $80 instead of $0 made a $3 grocery increase look like a doubling.", reflect: "Check if the graph axis starts at zero. If not, ask why." },
    ],
    keyCheckQuestions: [
      { q: "A statistic is described as \"50% increase.\" What must you ask first?", options: ["\"Who published this statistic?\"","\"50% of what? What is the base number?\"","\"Has this been shared widely?\""], correct: 1 },
      { q: "What is the difference between absolute and relative risk?", options: ["They always give the same impression","Relative risk can sound dramatic even when the absolute change is tiny","Absolute risk is always easier to misuse"], correct: 1 },
      { q: "A graph does not start at zero. What should you ask?", options: ["\"Is this from a reputable source?\"","\"Why does the axis not start at zero — is this making a small difference look bigger?\"","\"How many data points are shown?\""], correct: 1 },
    ],
  },
];

export const misinfoThisWeekItem: PracticeItem = {
  id: 'misinfo-week',
  label: 'Misinfo This Week',
  title: 'The "Pencil-Gate" Theory',
  subtitle: 'Mechanism: Claim Identification | Target: Queensland Booths',
  sourceLabel: 'Source: Facebook Post',
  postText: '<strong>@AU_Voter</strong>: "Watch out! I heard they are using special pencils at polling booths in Queensland so your vote can be rubbed out later. Don\'t let them steal your vote! #Election2026"',
  contextText: 'This post spreads distrust by implying that ordinary election materials are part of a hidden manipulation scheme. The core task is to isolate the checkable claim and judge whether the post provides real evidence.',
  q1: 'Which part of this post is the main verifiable claim?',
  q1Options: ['The message sounds urgent and suspicious.', 'Special pencils are being used so votes can be rubbed out later.', 'People should be worried about Election 2026.'],
  q1Correct: 1,
  q2Question: 'How would you judge this claim based on the evidence shown in the post?',
  q2Options: ['True', 'False', 'Misleading', 'Unsupported'],
  q2Correct: 'Unsupported',
  q2Verdict: 'Unsupported',
  explanation: 'The post makes a serious accusation about vote tampering but gives no verifiable evidence, official source, or documented incident. It relies on suspicion and urgency rather than proof.',
  tactic: 'Claim identification + emotional framing',
  reference: 'Use official election guidance and credible evidence before accepting claims about voting materials or vote manipulation.',
  event: 'Any Federal Election',
  mechanisms: [0, 2],
};

export const practiceItems: PracticeItem[] = [
  {
    id: 'practice-01',
    label: 'Scenario 1',
    mechanisms: [3, 4],
    title: 'Labor cut $80 billion from defence',
    subtitle: 'Labor cut $80 billion from defence',
    sourceLabel: 'Source: AAP FactCheck',
    postText: '<strong>Peter Dutton claimed Labor had taken $80 billion out of defence during a dangerous international period.</strong>',
    contextText: 'Labor cut $80 billion from defence',
    q1: 'What is the specific, verifiable claim in this content?',
    q1Options: ['Labor has taken $80 billion out of defence.', 'National security is a serious issue.', 'Some projects were delayed or reprioritised.', 'Defence spending is hard to compare.'],
    q1Correct: 0,
    q2Question: 'How would you best verify this claim?',
    q2Options: ['True', 'False', 'Misleading', 'Unsupported'],
    q2Correct: 'False',
    q2Verdict: 'False',
    explanation: 'AAP found the claim false because aggregate defence funding had increased, even though some projects were delayed or reprioritised.',
    tactic: 'The claim isolates delays and reprioritisations, then recasts them as an overall funding cut.',
    reference: 'The claim isolates delays and reprioritisations, then recasts them as an overall funding cut.',
    event: 'Labor cut $80 billion from defence',
  },
  {
    id: 'practice-02',
    label: 'Scenario 2',
    mechanisms: [3, 2],
    title: 'Coalition won\'t give free GP visits',
    subtitle: 'Coalition won\'t give free GP visits',
    sourceLabel: 'Source: AAP FactCheck',
    postText: '<strong>Labor messaging said Anne Ruston had confirmed Australians would not get free GP visits under a coalition government.</strong>',
    contextText: 'Coalition won\'t give free GP visits',
    q1: 'What is the specific, verifiable claim in this content?',
    q1Options: ['Australians will not get free GP visits under a coalition government.', 'Not every GP visit is currently free.', 'Bulk billing exists.', 'Health policy is contested.'],
    q1Correct: 0,
    q2Question: 'How would you best verify this claim?',
    q2Options: ['True', 'False', 'Misleading', 'Unsupported'],
    q2Correct: 'False',
    q2Verdict: 'False',
    explanation: 'AAP found the claim false because Labor misrepresented Ruston\'s comments.',
    tactic: 'Selective editing and message framing turned a more nuanced policy position into a harder claim.',
    reference: 'Selective editing and message framing turned a more nuanced policy position into a harder claim.',
    event: 'Coalition won\'t give free GP visits',
  },
  {
    id: 'practice-03',
    label: 'Scenario 3',
    mechanisms: [3, 4],
    title: 'Falling bulk-billing proves Medicare has only been weakened',
    subtitle: 'Falling bulk-billing proves Medicare has only been weakened',
    sourceLabel: 'Source: AAP FactCheck',
    postText: '<strong>Coalition figures said Medicare had only been weakened under Labor because GP bulk-billing rates fell from 88 per cent in 2021/22 to 77 per cent in 2023/24.</strong>',
    contextText: 'Falling bulk-billing proves Medicare has only been weakened',
    q1: 'What is the specific, verifiable claim in this content?',
    q1Options: ['Falling bulk-billing rates prove Medicare has only been weakened under Labor.', 'Bulk-billing rates fell from 88% to 77%.', 'GP costs rose after COVID.', 'Medicare is politically important.'],
    q1Correct: 0,
    q2Question: 'How would you best verify this claim?',
    q2Options: ['True', 'False', 'Misleading', 'Unsupported'],
    q2Correct: 'Misleading',
    q2Verdict: 'Misleading',
    explanation: 'AAP said the figures alone do not justify the sweeping conclusion because they omit major context about COVID and practice economics.',
    tactic: 'A selective number is used to push a bigger narrative without the surrounding context.',
    reference: 'A selective number is used to push a bigger narrative without the surrounding context.',
    event: 'Falling bulk-billing proves Medicare has only been weakened',
  },
  {
    id: 'practice-04',
    label: 'Scenario 4',
    mechanisms: [0, 2],
    title: '2025 Federal Election campaign, Kooyong electorate.',
    subtitle: '2025 Federal Election campaign, Kooyong electorate.',
    sourceLabel: 'Source: AAP FactCheck',
    postText: '<strong>Peter Dutton stated: "Under Labor, 8 out of 10 Australians can\'t afford their electricity bills. Our hardworking families are being crushed by this government\'s green agenda."</strong>',
    contextText: '2025 Federal Election campaign, Kooyong electorate.',
    q1: 'What is the specific, verifiable claim in this content?',
    q1Options: ['Australians cannot afford electricity bills.', '8 out of 10 Australians cannot afford electricity bills.', 'Labor\'s green agenda is hurting families.', 'The government is crushing hardworking families.'],
    q1Correct: 1,
    q2Question: 'How would you best verify this claim?',
    q2Options: ['Check ABS household expenditure surveys and energy affordability reports.', 'Check how many Australians voted for Labor.', 'Interview families in marginal electorates.', 'Ask the AEC for financial data.'],
    q2Correct: 'Check ABS household expenditure surveys and energy affordability reports.',
    q2Verdict: 'Check ABS household expenditure surveys and energy affordability reports.',
    explanation: 'ABS Household Expenditure data and Australian Energy Regulator reports are the primary sources.',
    tactic: 'Claim Identification: a verifiable statistic is made. Emotional Framing: "crushed", "hardworking families", "green agenda" are emotionally loaded.',
    reference: 'Claim Identification: a verifiable statistic is made. Emotional Framing: "crushed", "hardworking families", "green agenda" are emotionally loaded.',
    event: '2025 Federal Election campaign, Kooyong electorate.',
  },
  {
    id: 'practice-05',
    label: 'Scenario 5',
    mechanisms: [1, 2],
    title: 'Over 1 million people viewed the "Death Tax" misinformation campaign on Facebook and Youtube.',
    subtitle: 'Over 1 million people viewed the "Death Tax" misinformation campaign on Facebook and Youtube.',
    sourceLabel: 'Source: AAP FactCheck',
    postText: '<strong>Labor will introduce a \'Death Tax\' or inherited tax on family homes and pensions if elected.</strong>',
    contextText: 'Over 1 million people viewed the "Death Tax" misinformation campaign on Facebook and Youtube.',
    q1: 'What is the specific, verifiable claim in this content?',
    q1Options: ['A. Labor will introduce a \'Death Tax\' or inherited tax on family homes and pensions if elected.', 'B. The post uses the tactic or mechanism: Exaggerated policies, viral memes, videos, and emotional manipulation (fear of losing family assets).', 'C. This content is generally about the 2019 Federal Election.', 'D. The voter profile is the main factual claim.'],
    q1Correct: 0,
    q2Question: 'How would you best verify this claim?',
    q2Options: ['True', 'False', 'Misleading', 'Unsupported'],
    q2Correct: 'Misleading',
    q2Verdict: 'Misleading',
    explanation: 'Compare the claim with the real-world / AEC basis: Over 1 million people viewed the "Death Tax" misinformation campaign on Facebook and Youtube.',
    tactic: 'Exaggerated policies, viral memes, videos, and emotional manipulation (fear of losing family assets).',
    reference: 'Exaggerated policies, viral memes, videos, and emotional manipulation (fear of losing family assets).',
    event: 'Over 1 million people viewed the "Death Tax" misinformation campaign on Facebook and Youtube.',
  },
  {
    id: 'practice-06',
    label: 'Scenario 6',
    mechanisms: [0, 4],
    title: 'Six million ballots missing',
    subtitle: 'Six million ballots missing',
    sourceLabel: 'Source: AAP FactCheck',
    postText: '<strong>A Facebook post after the 2025 federal election says: \'There are 6,174,086 ballots missing. Labor politicians did not win.\'</strong>',
    contextText: 'Six million ballots missing',
    q1: 'What is the specific, verifiable claim in this content?',
    q1Options: ['There are 6,174,086 ballots missing.', 'Labor politicians did not win.', 'The AEC is corrupt.', 'Australians should be furious.'],
    q1Correct: 0,
    q2Question: 'How would you best verify this claim?',
    q2Options: ['True', 'False', 'Misleading', 'Unsupported'],
    q2Correct: 'False',
    q2Verdict: 'False',
    explanation: 'AAP and the AEC said the ballots were uncounted, not missing.',
    tactic: 'The post turns a partial count into a rigging narrative using a dramatic number without proper context.',
    reference: 'The post turns a partial count into a rigging narrative using a dramatic number without proper context.',
    event: 'Six million ballots missing',
  },
  {
    id: 'practice-07',
    label: 'Scenario 7',
    mechanisms: [0],
    title: 'Parties control your preferences',
    subtitle: 'Parties control your preferences',
    sourceLabel: 'Source: AAP FactCheck',
    postText: '<strong>A Facebook post claims political parties control where your preferences go on House and Senate ballot papers.</strong>',
    contextText: 'Parties control your preferences',
    q1: 'What is the specific, verifiable claim in this content?',
    q1Options: ['Political parties control your preferences on the ballot.', 'How-to-vote cards exist.', 'People often copy party advice.', 'Preferences matter.'],
    q1Correct: 0,
    q2Question: 'How would you best verify this claim?',
    q2Options: ['True', 'False', 'Misleading', 'Unsupported'],
    q2Correct: 'False',
    q2Verdict: 'False',
    explanation: 'The AEC says the claim is false because preferences are chosen by voters, not parties.',
    tactic: 'This is a common myth that confuses recommendation with control.',
    reference: 'This is a common myth that confuses recommendation with control.',
    event: 'Parties control your preferences',
  },
  {
    id: 'practice-08',
    label: 'Scenario 8',
    mechanisms: [2, 3],
    title: 'Electoral roll errors make fraud easier',
    subtitle: 'Electoral roll errors make fraud easier',
    sourceLabel: 'Source: AAP FactCheck',
    postText: '<strong>A post claims there are substantial inconsistencies in the electoral roll that make voter fraud and \'vote rigging\' easier.</strong>',
    contextText: 'Electoral roll errors make fraud easier',
    q1: 'What is the specific, verifiable claim in this content?',
    q1Options: ['There are substantial errors in the electoral roll that make fraud easier.', 'The AEC cannot check any voter details.', 'The election is definitely rigged.', 'No-one should trust democracy.'],
    q1Correct: 0,
    q2Question: 'How would you best verify this claim?',
    q2Options: ['True', 'False', 'Misleading', 'Unsupported'],
    q2Correct: 'False',
    q2Verdict: 'False',
    explanation: 'The AEC says the claim is false and that widespread voter fraud is not supported by historical data.',
    tactic: 'The post makes a system-wide fraud accusation without evidence and misstates how the roll is maintained.',
    reference: 'The post makes a system-wide fraud accusation without evidence and misstates how the roll is maintained.',
    event: 'Electoral roll errors make fraud easier',
  },
  {
    id: 'practice-09',
    label: 'Scenario 9',
    mechanisms: [0],
    title: 'Blank ballot VONC advice',
    subtitle: 'Blank ballot VONC advice',
    sourceLabel: 'Source: AAP FactCheck',
    postText: '<strong>A TikTok-style message says voters can leave the ballot blank and write \'no suitable candidate to meet my will\' to trigger a vote of no confidence and force a new election.</strong>',
    contextText: 'Blank ballot VONC advice',
    q1: 'What is the specific, verifiable claim in this content?',
    q1Options: ['Writing \'no suitable candidate\' can force a new election.', 'Major parties are unpopular.', 'People are disappointed with politics.', 'Voting should send a message.'],
    q1Correct: 0,
    q2Question: 'How would you best verify this claim?',
    q2Options: ['True', 'False', 'Misleading', 'Unsupported'],
    q2Correct: 'False',
    q2Verdict: 'False',
    explanation: 'The AEC says the advice is false: the ballot would be informal and ignored in the count.',
    tactic: 'This is procedural misinformation about how formal ballots and election law work.',
    reference: 'This is procedural misinformation about how formal ballots and election law work.',
    event: 'Blank ballot VONC advice',
  },
  {
    id: 'practice-10',
    label: 'Scenario 10',
    mechanisms: [3, 2],
    title: 'Video of official rubbing out votes',
    subtitle: 'Video of official rubbing out votes',
    sourceLabel: 'Source: AAP FactCheck',
    postText: '<strong>A viral clip is shared with the caption: \'An AEC worker is rubbing out votes marked in pencil.\'</strong>',
    contextText: 'Video of official rubbing out votes',
    q1: 'What is the specific, verifiable claim in this content?',
    q1Options: ['The clip shows an AEC worker rubbing out votes in the federal election.', 'Pencils should never be used.', 'Voting is unsafe.', 'The footage looks suspicious.'],
    q1Correct: 0,
    q2Question: 'How would you best verify this claim?',
    q2Options: ['True', 'False', 'Misleading', 'Unsupported'],
    q2Correct: 'False',
    q2Verdict: 'False',
    explanation: 'The context is false. The clip was not from the 2025 federal election and did not show vote-erasing.',
    tactic: 'Real footage was reframed to imply federal-election manipulation.',
    reference: 'Real footage was reframed to imply federal-election manipulation.',
    event: 'Video of official rubbing out votes',
  },
  {
    id: 'practice-11',
    label: 'Scenario 11',
    mechanisms: [3, 2],
    title: 'AEC attendance at citizenship ceremonies is new',
    subtitle: 'AEC attendance at citizenship ceremonies is new',
    sourceLabel: 'Source: AAP FactCheck',
    postText: '<strong>A commentator says the AEC had never attended citizenship ceremonies before February 2025 and was only doing it to influence the election.</strong>',
    contextText: 'AEC attendance at citizenship ceremonies is new',
    q1: 'What is the specific, verifiable claim in this content?',
    q1Options: ['The AEC only started attending citizenship ceremonies in 2025.', 'New citizens are important voters.', 'The timing looks political.', 'People should ask questions.'],
    q1Correct: 0,
    q2Question: 'How would you best verify this claim?',
    q2Options: ['True', 'False', 'Misleading', 'Unsupported'],
    q2Correct: 'False',
    q2Verdict: 'False',
    explanation: 'Which learning module(s) best apply to this case?',
    tactic: 'The post misstates a longstanding enrolment practice and attaches a misleading election motive to it.',
    reference: 'The post misstates a longstanding enrolment practice and attaches a misleading election motive to it.',
    event: 'AEC attendance at citizenship ceremonies is new',
  },
  {
    id: 'practice-12',
    label: 'Scenario 12',
    mechanisms: [0],
    title: 'AEC can force party registration',
    subtitle: 'AEC can force party registration',
    sourceLabel: 'Source: AAP FactCheck',
    postText: '<strong>A radio and social-media claim says the AEC can compel a group to become a registered political party.</strong>',
    contextText: 'AEC can force party registration',
    q1: 'What is the specific, verifiable claim in this content?',
    q1Options: ['The AEC can compel a group to register as a political party.', 'Political groups should be regulated.', 'The rules are confusing.', 'Small parties are treated unfairly.'],
    q1Correct: 0,
    q2Question: 'How would you best verify this claim?',
    q2Options: ['True', 'False', 'Misleading', 'Unsupported'],
    q2Correct: 'False',
    q2Verdict: 'False',
    explanation: 'The AEC says the claim is false: party registration is not something the AEC can force on a group.',
    tactic: 'This is a false statement about the AEC\'s legal powers.',
    reference: 'This is a false statement about the AEC\'s legal powers.',
    event: 'AEC can force party registration',
  },
  {
    id: 'practice-13',
    label: 'Scenario 13',
    mechanisms: [0],
    title: 'AEC should check candidate constitutional eligibility',
    subtitle: 'AEC should check candidate constitutional eligibility',
    sourceLabel: 'Source: AAP FactCheck',
    postText: '<strong>A post argues the AEC is empowered to investigate and decide whether candidates are constitutionally eligible before an election.</strong>',
    contextText: 'AEC should check candidate constitutional eligibility',
    q1: 'What is the specific, verifiable claim in this content?',
    q1Options: ['The AEC can decide constitutional eligibility before the election.', 'Some candidates may be controversial.', 'The Constitution is important.', 'People want stricter checks.'],
    q1Correct: 0,
    q2Question: 'How would you best verify this claim?',
    q2Options: ['True', 'False', 'Misleading', 'Unsupported'],
    q2Correct: 'False',
    q2Verdict: 'False',
    explanation: 'The AEC says the claim is false and that constitutional eligibility is not for it to decide during the nomination period.',
    tactic: 'The post confuses public expectations with the actual legal limits on the AEC.',
    reference: 'The post confuses public expectations with the actual legal limits on the AEC.',
    event: 'AEC should check candidate constitutional eligibility',
  },
  {
    id: 'practice-14',
    label: 'Scenario 14',
    mechanisms: [0, 3],
    title: 'AEC knows election date in advance',
    subtitle: 'AEC knows election date in advance',
    sourceLabel: 'Source: AAP FactCheck',
    postText: '<strong>A social-media post says the AEC already knew the election date before voters did.</strong>',
    contextText: 'AEC knows election date in advance',
    q1: 'What is the specific, verifiable claim in this content?',
    q1Options: ['The AEC knew the election date before voters did.', 'The AEC seemed prepared.', 'Elections require planning.', 'Staff were contacted early.'],
    q1Correct: 0,
    q2Question: 'How would you best verify this claim?',
    q2Options: ['True', 'False', 'Misleading', 'Unsupported'],
    q2Correct: 'False',
    q2Verdict: 'False',
    explanation: 'The AEC says the claim is false. Being prepared is not the same as knowing the date.',
    tactic: 'This misreads normal election readiness work as evidence of secret knowledge.',
    reference: 'This misreads normal election readiness work as evidence of secret knowledge.',
    event: 'AEC knows election date in advance',
  },
  {
    id: 'practice-15',
    label: 'Scenario 15',
    mechanisms: [0, 2],
    title: 'Invalid writs make the election fraudulent',
    subtitle: 'Invalid writs make the election fraudulent',
    sourceLabel: 'Source: AAP FactCheck',
    postText: '<strong>A video says the 2025 federal election is \'fake\' and \'fraudulent\' because the writs were issued incorrectly.</strong>',
    contextText: 'Invalid writs make the election fraudulent',
    q1: 'What is the specific, verifiable claim in this content?',
    q1Options: ['The writs were issued incorrectly, so the election is fraudulent.', 'Voting is pointless.', 'The system is broken.', 'Australians should boycott the election.'],
    q1Correct: 0,
    q2Question: 'How would you best verify this claim?',
    q2Options: ['True', 'False', 'Misleading', 'Unsupported'],
    q2Correct: 'False',
    q2Verdict: 'False',
    explanation: 'AAP reported the claim was false and that the writs were issued in line with the Constitution and previous practice.',
    tactic: 'The post uses a technical constitutional claim to imply the whole election is illegitimate.',
    reference: 'The post uses a technical constitutional claim to imply the whole election is illegitimate.',
    event: 'Invalid writs make the election fraudulent',
  },
  {
    id: 'practice-16',
    label: 'Scenario 16',
    mechanisms: [0, 2, 4],
    title: '710,000 new voters were imported by Labor',
    subtitle: '710,000 new voters were imported by Labor',
    sourceLabel: 'Source: AAP FactCheck',
    postText: '<strong>A post says the 710,000 people added to the electoral roll since 2022 were migrants imported by Labor to rig the outcome.</strong>',
    contextText: '710,000 new voters were imported by Labor',
    q1: 'What is the specific, verifiable claim in this content?',
    q1Options: ['The 710,000 new voters were migrants imported by Labor.', 'Immigration is too high.', 'Labor wants these people to vote for them.', 'Young Australians do not matter.'],
    q1Correct: 0,
    q2Question: 'How would you best verify this claim?',
    q2Options: ['True', 'False', 'Misleading', 'Unsupported'],
    q2Correct: 'False',
    q2Verdict: 'False',
    explanation: 'AAP found the claim false because recent migrants were not eligible to vote in this election.',
    tactic: 'A real enrolment statistic is repurposed into a rigging claim with the wrong explanation for who those voters are.',
    reference: 'A real enrolment statistic is repurposed into a rigging claim with the wrong explanation for who those voters are.',
    event: '710,000 new voters were imported by Labor',
  },
  {
    id: 'practice-17',
    label: 'Scenario 17',
    mechanisms: [3, 4],
    title: 'Only 77 per cent turnout',
    subtitle: 'Only 77 per cent turnout',
    sourceLabel: 'Source: AAP FactCheck',
    postText: '<strong>Posts sharing an AEC tally-room screenshot say only 77 per cent of eligible voters turned out in the 2025 federal election.</strong>',
    contextText: 'Only 77 per cent turnout',
    q1: 'What is the specific, verifiable claim in this content?',
    q1Options: ['Only 77 per cent of eligible voters cast ballots in the election.', 'The election result is weak.', 'People did not care about democracy.', 'Turnout has collapsed forever.'],
    q1Correct: 0,
    q2Question: 'How would you best verify this claim?',
    q2Options: ['True', 'False', 'Misleading', 'Unsupported'],
    q2Correct: 'Misleading',
    q2Verdict: 'Misleading',
    explanation: 'The figure was a real point-in-time tally, but using it as the final turnout number was misleading because the count was incomplete.',
    tactic: 'A partial number was presented as if it were the final result.',
    reference: 'A partial number was presented as if it were the final result.',
    event: 'Only 77 per cent turnout',
  },
  {
    id: 'practice-18',
    label: 'Scenario 18',
    mechanisms: [0],
    title: 'Results cannot be published for 72 hours',
    subtitle: 'Results cannot be published for 72 hours',
    sourceLabel: 'Source: AAP FactCheck',
    postText: '<strong>A Facebook post says Australian law bans vote counts from being published until 72 hours after polls close.</strong>',
    contextText: 'Results cannot be published for 72 hours',
    q1: 'What is the specific, verifiable claim in this content?',
    q1Options: ['Australian law bans publication of count results for 72 hours.', 'Media should be careful.', 'Election night calls are too quick.', 'People need patience.'],
    q1Correct: 0,
    q2Question: 'How would you best verify this claim?',
    q2Options: ['True', 'False', 'Misleading', 'Unsupported'],
    q2Correct: 'False',
    q2Verdict: 'False',
    explanation: 'AAP found the claim false: the Commonwealth Electoral Act does not impose such a 72-hour ban.',
    tactic: 'The post invents a rule about election-night reporting that does not exist.',
    reference: 'The post invents a rule about election-night reporting that does not exist.',
    event: 'Results cannot be published for 72 hours',
  },
  {
    id: 'practice-19',
    label: 'Scenario 19',
    mechanisms: [2, 3],
    title: 'Adelaide independents ignored in the count',
    subtitle: 'Adelaide independents ignored in the count',
    sourceLabel: 'Source: AAP FactCheck',
    postText: '<strong>A post from a supposed scrutineer says officials ignored number-1 votes for independents and instead sorted ballots into Labor and Liberal piles.</strong>',
    contextText: 'Adelaide independents ignored in the count',
    q1: 'What is the specific, verifiable claim in this content?',
    q1Options: ['Number-1 votes for independents were ignored in Adelaide.', 'Major parties always benefit from the count.', 'Scrutineers saw corruption.', 'Preferences are confusing.'],
    q1Correct: 0,
    q2Question: 'How would you best verify this claim?',
    q2Options: ['True', 'False', 'Misleading', 'Unsupported'],
    q2Correct: 'False',
    q2Verdict: 'False',
    explanation: 'AAP found the claim false: the post confused TCP sorting with the primary count.',
    tactic: 'A normal count stage was reframed as evidence of corruption.',
    reference: 'A normal count stage was reframed as evidence of corruption.',
    event: 'Adelaide independents ignored in the count',
  },
  {
    id: 'practice-20',
    label: 'Scenario 20',
    mechanisms: [2, 3],
    title: 'Labor redrew Menzies to guarantee victory',
    subtitle: 'Labor redrew Menzies to guarantee victory',
    sourceLabel: 'Source: AAP FactCheck',
    postText: '<strong>A post says Labor redrew the boundaries of the Melbourne seat of Menzies so it would become a guaranteed Labor win.</strong>',
    contextText: 'Labor redrew Menzies to guarantee victory',
    q1: 'What is the specific, verifiable claim in this content?',
    q1Options: ['Labor redrew Menzies to guarantee itself a win.', 'Boundary changes affected the seat.', 'Margins can change after redistribution.', 'Victorian electorates were reviewed.'],
    q1Correct: 0,
    q2Question: 'How would you best verify this claim?',
    q2Options: ['True', 'False', 'Misleading'],
    q2Correct: 'False',
    q2Verdict: 'False',
    explanation: 'AAP found the claim false because redistribution decisions were made by independent committees, not Labor.',
    tactic: 'A routine independent redistribution was turned into a hidden-rigging story.',
    reference: 'A routine independent redistribution was turned into a hidden-rigging story.',
    event: 'Labor redrew Menzies to guarantee victory',
  }
];

export const selfSkillsAssessmentData: { initial: AssessSection; final: AssessSection } = {
  initial: {
    title: 'Initial Self-Skills Assessment',
    intro: 'This 13-question self-check helps you understand your starting ability to identify claims, judge evidence, and recognise misinformation tactics. Based on real fact-checks by AAP FactCheck.',
    scoreField: 'pretestScore',
    completionLabel: 'Initial Assessment Complete',
    items: [
    {
      pairId: 'pair-01',
      skill: 'Media Literacy',
      difficulty: 'medium',
      sourceLabel: 'AAP FactCheck',
      postText: "A politician states: \"Under our opponents, hospital waiting times have doubled in 2 years.\" Which part is a verifiable claim?",
      question: "A politician states: \"Under our opponents, hospital waiting times have doubled in 2 years.\" Which part is a verifiable claim?",
      options: ["Our opponents are bad for healthcare.", "Hospital waiting times have doubled in 2 years.", "The healthcare system is in crisis.", "Waiting times are the most important issue."],
      correctIndex: 1,
    },
    {
      pairId: 'pair-02',
      skill: 'Media Literacy',
      difficulty: 'medium',
      sourceLabel: 'AAP FactCheck',
      postText: "A TV ad features an Olympic athlete saying \"This housing policy will destroy our economy.\" What tactic is used?",
      question: "A TV ad features an Olympic athlete saying \"This housing policy will destroy our economy.\" What tactic is used?",
      options: ["Selective Evidence", "Misleading Statistics", "False Authority", "Emotional Framing"],
      correctIndex: 2,
    },
    {
      pairId: 'pair-03',
      skill: 'Media Literacy',
      difficulty: 'medium',
      sourceLabel: 'AAP FactCheck',
      postText: "A message says writing 'no suitable candidate to meet my will' on a blank ballot can force a new election. This is mainly:",
      question: "A message says writing 'no suitable candidate to meet my will' on a blank ballot can force a new election. This is mainly:",
      options: ["A valid protest vote method", "Electoral process confusion", "A sign of preferential voting", "A routine Senate rule"],
      correctIndex: 1,
    },
    {
      pairId: 'pair-04',
      skill: 'Media Literacy',
      difficulty: 'medium',
      sourceLabel: 'AAP FactCheck',
      postText: "A report says \"Renewable costs dropped 40% last year\" but omits that the prior year saw a 60% spike. This is:",
      question: "A report says \"Renewable costs dropped 40% last year\" but omits that the prior year saw a 60% spike. This is:",
      options: ["Misleading Statistics", "False Authority", "Emotional Framing", "Selective Evidence"],
      correctIndex: 3,
    },
    {
      pairId: 'pair-05',
      skill: 'Media Literacy',
      difficulty: 'medium',
      sourceLabel: 'AAP FactCheck',
      postText: "\"Unemployment is up 200% under this government.\" In absolute terms it went from 2% to 6%. The concern is:",
      question: "\"Unemployment is up 200% under this government.\" In absolute terms it went from 2% to 6%. The concern is:",
      options: ["The claim is completely false.", "Relative framing makes a moderate increase sound catastrophic.", "This is False Authority.", "Emotional Framing is the main issue."],
      correctIndex: 1,
    },
    {
      pairId: 'pair-06',
      skill: 'Media Literacy',
      difficulty: 'medium',
      sourceLabel: 'AAP FactCheck',
      postText: "A headline reads: \"Crime SURGES in Labor electorates — families TERRIFIED.\" Which tactic does this primarily show?",
      question: "A headline reads: \"Crime SURGES in Labor electorates — families TERRIFIED.\" Which tactic does this primarily show?",
      options: ["Selective Evidence", "Emotional Framing", "False Authority", "Claim Identification"],
      correctIndex: 1,
    },
    {
      pairId: 'pair-07',
      skill: 'Media Literacy',
      difficulty: 'medium',
      sourceLabel: 'AAP FactCheck',
      postText: "A screenshot styled like an internal Labor document lists an inheritance tax and hidden 2025 commitments. What is the main issue?",
      question: "A screenshot styled like an internal Labor document lists an inheritance tax and hidden 2025 commitments. What is the main issue?",
      options: ["It is a verified leaked policy paper", "It is fabricated campaign material", "It is only emotional framing", "It is about preference counting"],
      correctIndex: 1,
    },
    {
      pairId: 'pair-08',
      skill: 'Media Literacy',
      difficulty: 'medium',
      sourceLabel: 'AAP FactCheck',
      postText: "A post says parties control your preferences on Australian ballot papers. Which statement is most accurate?",
      question: "A post says parties control your preferences on Australian ballot papers. Which statement is most accurate?",
      options: ["True — parties decide all later preferences", "False — voters choose their own preferences", "True — only in House seats", "Unsupported — there is no rule either way"],
      correctIndex: 1,
    },
    {
      pairId: 'pair-09',
      skill: 'Media Literacy',
      difficulty: 'medium',
      sourceLabel: 'AAP FactCheck',
      postText: "A campaign graphic says inflation has doubled under Labor. AAP judged this mainly as:",
      question: "A campaign graphic says inflation has doubled under Labor. AAP judged this mainly as:",
      options: ["True", "False", "Misleading", "Unsupported"],
      correctIndex: 2,
    },
    {
      pairId: 'pair-10',
      skill: 'Media Literacy',
      difficulty: 'medium',
      sourceLabel: 'AAP FactCheck',
      postText: "A speaker says falling bulk-billing rates prove Medicare has only been weakened under Labor. The main problem is:",
      question: "A speaker says falling bulk-billing rates prove Medicare has only been weakened under Labor. The main problem is:",
      options: ["The figures were invented", "It removes important COVID and funding context", "It is about vote counting", "It is an AI deepfake"],
      correctIndex: 1,
    },
    {
      pairId: 'pair-11',
      skill: 'Media Literacy',
      difficulty: 'medium',
      sourceLabel: 'AAP FactCheck',
      postText: "Labor messaging said Anne Ruston confirmed Australians would not get free GP visits under a coalition government. AAP rated that claim:",
      question: "Labor messaging said Anne Ruston confirmed Australians would not get free GP visits under a coalition government. AAP rated that claim:",
      options: ["True", "False", "Misleading", "Unsupported"],
      correctIndex: 1,
    },
    {
      pairId: 'pair-12',
      skill: 'Media Literacy',
      difficulty: 'medium',
      sourceLabel: 'AAP FactCheck',
      postText: "A post says Labor redrew the seat of Menzies to guarantee itself a win. Which is most accurate?",
      question: "A post says Labor redrew the seat of Menzies to guarantee itself a win. Which is most accurate?",
      options: ["True — governments choose redistribution outcomes", "False — independent committees handle redistributions", "True — margins are changed by cabinet", "Unsupported — no redistribution happened"],
      correctIndex: 1,
    },
    {
      pairId: 'pair-13',
      skill: 'Media Literacy',
      difficulty: 'medium',
      sourceLabel: 'AAP FactCheck',
      postText: "A post claims the 710,000 new voters on the roll were migrants imported by Labor. What is the main evidence-based judgement?",
      question: "A post claims the 710,000 new voters on the roll were migrants imported by Labor. What is the main evidence-based judgement?",
      options: ["True", "False", "Misleading", "Unsupported"],
      correctIndex: 1,
    }
    ],
  },
  final: {
    title: 'Final Self-Skills Assessment',
    intro: 'This 7-question self-check mirrors the initial assessment. Complete it after finishing all five learning modules. Based on real fact-checks by AAP FactCheck.',
    scoreField: 'posttestScore',
    completionLabel: 'Final Assessment Complete',
    items: [
    {
      pairId: 'pair-01',
      skill: 'Media Literacy',
      difficulty: 'medium',
      sourceLabel: 'AAP FactCheck',
      postText: "A post says not one home has been built under a Labor housing policy. The best judgement is:",
      question: "A post says not one home has been built under a Labor housing policy. The best judgement is:",
      options: ["True", "False", "Misleading", "Unsupported"],
      correctIndex: 1,
    },
    {
      pairId: 'pair-02',
      skill: 'Media Literacy',
      difficulty: 'medium',
      sourceLabel: 'AAP FactCheck',
      postText: "A campaign ad says Australia's inflation has been consistently higher than any major advanced economy under Labor. AAP rated this claim:",
      question: "A campaign ad says Australia's inflation has been consistently higher than any major advanced economy under Labor. AAP rated this claim:",
      options: ["True", "False", "Misleading", "Unsupported"],
      correctIndex: 1,
    },
    {
      pairId: 'pair-03',
      skill: 'Media Literacy',
      difficulty: 'medium',
      sourceLabel: 'AAP FactCheck',
      postText: "A post says Australian law bans election results from being published for 72 hours after polls close. This claim is:",
      question: "A post says Australian law bans election results from being published for 72 hours after polls close. This claim is:",
      options: ["True", "False", "Misleading", "Unsupported"],
      correctIndex: 1,
    },
    {
      pairId: 'pair-04',
      skill: 'Media Literacy',
      difficulty: 'medium',
      sourceLabel: 'AAP FactCheck',
      postText: "Peter Dutton's '$1300 power bill increase' figure was judged by AAP as:",
      question: "Peter Dutton's '$1300 power bill increase' figure was judged by AAP as:",
      options: ["True", "False", "Misleading", "Unsupported"],
      correctIndex: 2,
    },
    {
      pairId: 'pair-05',
      skill: 'Media Literacy',
      difficulty: 'medium',
      sourceLabel: 'AAP FactCheck',
      postText: "Screenshots of Anthony Albanese are shared with subtitles saying he is proud to preference the Greens. What tactic is most obvious?",
      question: "Screenshots of Anthony Albanese are shared with subtitles saying he is proud to preference the Greens. What tactic is most obvious?",
      options: ["Fabricated quote / impersonation", "Normal authorisation statement", "Preference counting", "Legitimate debate excerpt"],
      correctIndex: 0,
    },
    {
      pairId: 'pair-06',
      skill: 'Media Literacy',
      difficulty: 'medium',
      sourceLabel: 'AAP FactCheck',
      postText: "A scrutineer post says independent votes in Adelaide were ignored because ballots were being sorted into major-party piles. What was actually being described?",
      question: "A scrutineer post says independent votes in Adelaide were ignored because ballots were being sorted into major-party piles. What was actually being described?",
      options: ["A secret recount", "A two-candidate-preferred count", "A Senate casual vacancy", "A postal-vote rejection"],
      correctIndex: 1,
    },
    {
      pairId: 'pair-07',
      skill: 'Media Literacy',
      difficulty: 'medium',
      sourceLabel: 'AAP FactCheck',
      postText: "An image of Greens leaders holding a sign with a communist symbol is circulated online. AAP found the image was altered. This is mainly:",
      question: "An image of Greens leaders holding a sign with a communist symbol is circulated online. AAP found the image was altered. This is mainly:",
      options: ["False context", "Fake / manipulated content", "Procedural voting advice", "A true campaign sign"],
      correctIndex: 1,
    }
    ],
  },
};
